name: Code Quality

on:
  push:
  pull_request:

jobs:
  quality:
    name: Code Quality Checks
    runs-on: ubuntu-latest
    continue-on-error: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install uv
        run: |
          python -m pip install --upgrade pip
          pip install uv

      - name: Sync quality deps
        run: uv sync --group quality

      - name: Cache pre-commit environments
        uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ runner.os }}-${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Run pre-commit on all files
        run: uv run pre-commit run --all-files
